### Compose ###
version: '3'

services:
  registry:
    restart: always
    build: registry
    ports:
      - 5000:5000
    volumes:
      - /path/data:/var/lib/registry
    container_name: "javacloud-registry"
  nexus:
    build: nexus
    image: localhost:5000/javacloud-nexus # goes to local registry
    ports:
     - "127.0.0.1:8081:8081"
    container_name: "javacloud-nexus"
  jenkins:
    build: jenkins
    ports:
     - "127.0.0.1:8082:8082"
    container_name: "javacloud-jenkins"
    volumes:
      - data-volume:/javacloud/datavolume
      #todo: remove this values in future (HOST:CONTAINER)
      #NOTE: This value must be identical with cloud.properties#ci.workspace.folder and relevant cloud-override.properties property
      #- /javacloud/datavolume/.ci_repositories:/javacloud/datavolume/.ci_repositories
      #- ./.ci_repositories:/var/jenkins_home/.ci_repositories/
      #NOTE: This value must be identical with cloud.properties#repository.base.folder and relevant cloud-override.properties property
      #- /javacloud/datavolume/.local_repositories:/javacloud/datavolume/.local_repositories
      #- ./.local_repositories:$HOME/.local_repositories
  alpine-java:
    build: alpine-java
    container_name: "javacloud-deployments"
  mysql:
    build: mysql
    ports:
    - "127.0.0.1:3306:3306"
    container_name: "javacloud-mysql"   
  mongodb:
    build: mongodb
    ports:
    - "127.0.0.1:27017:27017"
    #- "27017:27017"
    container_name: "javacloud-mongodb"
  git:
    build: git
    ports:
    - "127.0.0.1:9418:9418"
    volumes:
      - data-volume:/javacloud/datavolume
     #todo: remove this values in future (HOST:CONTAINER)
     #NOTE: This value must be identical with cloud.properties#repository.base.folder and relevant cloud-override.properties property
     #- /javacloud/datavolume/.local_repositories:/javacloud/datavolume/.local_repositories
     # - ./.local_repositories:$HOME/.local_repositories
    container_name: "javacloud-git"
  gitlab:
    build: gitlab
    ports:
    - "8083:8083"
    - "8322:8322"
    environment:
      GITLAB_OMNIBUS_CONFIG: |    
        external_url "http://#{host}/gitlab"
        nginx['listen_port'] = 8083
        gitlab_rails['gitlab_shell_ssh_port'] = 8322
    container_name: "javacloud-gitlab"
  sonarqube:
    build: sonarqube
    container_name: "javacloud-sonarqube"
  redis:
    image: "redis:alpine"
    container_name: "javacloud-redis"   
  webconsole:
    build: webconsole
    ports:
     - "127.0.0.1:8080:8080"
    volumes:
      - data-volume:/javacloud/datavolume
      #todo: remove this values in future (HOST:CONTAINER)
      #NOTE: This value must be identical with cloud.properties#ci.workspace.folder and relevant cloud-override.properties property
      #- /javacloud/datavolume/.ci_repositories:/javacloud/datavolume/.ci_repositories
      #- ./.ci_repositories:$HOME/.ci_repositories
      #NOTE: This value must be identical with cloud.properties#repository.base.folder and relevant cloud-override.properties property
      #- /javacloud/datavolume/.local_repositories:/javacloud/datavolume/.local_repositories
      #- ./.local_repositories:$HOME/.local_repositories
    container_name: "javacloud-webconsole"

volumes:
  data-volume: