version: '3'
services:
  apache2:
    build: apache2
    ports:
     - "80:80"
    container_name: "javacloud-apache2-http-proxy"
  redis:
    image: "redis:alpine"
    container_name: "javacloud-redis"   
    
