version: '3'
services:
  nexus:
    build: nexus
    ports:
     - "8081:8081"
    container_name: "javacloud-nexus"
  jenkins:
    build: jenkins
    ports:
     - "8082:8082"
    container_name: "javacloud-jenkins"
  alpine-java:
    build: alpine-java
    container_name: "javacloud-deployments"
  mysql:
    build: mysql
    container_name: "javacloud-mysql"   
  mongodb:
    build: mongodb
    container_name: "javacloud-mongodb"
  gitlab:
    build: gitlab
    ports:
    - "8083:8083"
    - "8322:8322"
    environment:    
    - GITLAB_HTTPS=false
    - GITLAB_PORT=8083
    - GITLAB_SSH_PORT=8322
    - GITLAB_RELATIVE_URL_ROOT=/gitlab
    container_name: "javacloud-gitlab"
  redis:
    image: "redis:alpine"
    container_name: "javacloud-redis"   
  webconsole:
    build: webconsole
    ports:
     - "8080:8080"    
    container_name: "javacloud-webconsole"
