version: '3'
services:
  apache2:
    build: apache2
    ports:
     - "80:80"
    container_name: "javacloud-apache2-http-proxy"
  alpine-java:
    build: alpine-java
    container_name: "javacloud-deployments"
  redis:
    image: "redis:alpine"
    container_name: "javacloud-redis"   
  webconsole:
    build: webconsole
    ports:
     - "8080:8080"    
    container_name: "javacloud-webconsole"
